name: ci
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
env:
  GO_VERSION: '1.20.x'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ${{env.GO_VERSION}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Build
        run: make build
      - name: Test
        run: make test
